### ISSUE TITLE
indigo release fails to build

### ISSUE THREAD

**Issue by tfoote** [ipab-slmc/pybind11_catkin#1]
It's failing on all platforms. 

Here's the output on amd64: http://build.ros.org/view/Ibin_uT32/job/Ibin_uT64__pybind11_catkin__ubuntu_trusty_amd64__binary/7/console
```
23:35:25 CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:298 (message):
23:35:25   catkin_package() include dir 'include' does not exist relative to
23:35:25   '/tmp/binarydeb/ros-indigo-pybind11-catkin-2.2.3'
23:35:25 Call Stack (most recent call first):
23:35:25   /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:100 (_catkin_package)
23:35:25   CMakeLists.txt:38 (catkin_package)
23:35:25 
23:35:25 
23:35:25 -- Configuring incomplete, errors occurred!
23:35:25 See also "/tmp/binarydeb/ros-indigo-pybind11-catkin-2.2.3/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
23:35:25 See also "/tmp/binarydeb/ros-indigo-pybind11-catkin-2.2.3/obj-x86_64-linux-gnu/CMakeFiles/CMakeError.log".
23:35:25 dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo returned exit code 1
23:35:25 make[1]: *** [override_dh_auto_configure] Error 2
23:35:25 make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-pybind11-catkin-2.2.3'
23:35:25 make: *** [build] Error 2
23:35:25 dpkg-buildpackage: error: debian/rules build gave error exit status 2
23:35:25 E: Building failed
23:35:25 Traceback (most recent call last):
23:35:25   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 138, in build_binarydeb
23:35:25     subprocess.check_call(cmd, cwd=source_dir)
23:35:25   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
23:35:25     raise CalledProcessError(retcode, cmd)
23:35:25 # END SUBSECTION
23:35:25 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-pybind11-catkin']' returned non-zero exit status 1
```

**Comment by wxmerkt** [comment]
It's now building on the buildfarm - closing this issue. Will release for kinetic and melodic shortly.
